### PR TITLE
minor: add vim files to .gitignore

### PR DESCRIPTION
**Pull request by fridokus**
reference: 
https://github.com/github/gitignore/blob/master/Global/Vim.gitignore

### CODE REVIEW

**Comment by Fonta1n3** [comment]
Hey thanks very much for the PR. Please do read the Contributing instructions here: https://github.com/Fonta1n3/FullyNoded#contributing

**Comment by fridokus** [comment]
Updated with signature

**Comment by Fonta1n3** [comment]
Hey, sorry for the massive delay! Can you share a reasoning for adding this?

**Comment by fridokus** [comment]
Yes. This is for people like me who write all code in vim, so that we don’t
accidentally add hidden files created by vim.

**Pull request merged**
