### PR TITLE
fix: correct unit for mempool transactions

### PR DESCRIPTION
**Pull request by fridokus**
Change unit for number of transactions in mempool from "mempool" to "transactions".

See attached image.

image_123986672

### CODE REVIEW

**Comment by Fonta1n3** [comment]
hmm the mempool consists of pending transactions, which is why I label it as transactions. "24,876 mempool" does not really make sense to me.

**Comment by fridokus** [comment]
Yes I agreee with you. 

That’s the change I’m making!

check the commit ;)

**Comment by fridokus** [comment]
The screenshot is how it currently looks @Fonta1n3

**Comment by Fonta1n3** [comment]
Ahhh gotcha 😂 Will fix, thanks for that! If you fill out the CLA and sign your commit with pgp i will happily merge.

**Comment by fridokus** [comment]
Updated commit with verified signature

**Pull request merged**
