### PR TITLE
latest topics added

### PR DESCRIPTION
**Pull request by henkvancann**

### CODE REVIEW

**Comment by Fonta1n3** [comment]
Ah, I made changes to the overall format. Please pull from master to update your fork then add these again, I tried to give you a heads up about that via DM in telegram. You can see the changes I made. Basically i got rid of the “sure” levels as I want all answers to be matter of fact (not necessarily verbatim from the chat) and made some changes to he format.

**Comment by Fonta1n3** [comment]
Thanks Henk, there seems to be a conflict so I can not merge it automatically, can you try and resolve it? 

Also please remove the FN2 comparison, I think it just generates more confusion. They are separate apps, users can just try both and see the differences themselves.

**Comment by henkvancann** [comment]
Hi Fonta1n3,

I’ve tried merging the two, and I will continue to do so. It’s just that I need to practise git more, to get it right. It is a good exercise.

Sorry I am not at the right level of knowledge and experience yet for the comparison table. I’ll write a comparison on my personal github page and on my personal account. When even a comparison between two apps generates confusion; just image what both apps themselves do. I think in the end, newcomers need one, badly.

A comparison is normal thing on the web. We should be able to explain to people in clear wording what the differences and similarities are, at all times? So I might have to create a much better piece of text & table, agreed, but I’ll certainly continue to try and do so. I invite you to mentor me now and again on my journey and review the page. Deal?

Best regards, Henk

**Comment by henkvancann** [comment]
I an still figuring out how to merge the two original conflicting files QandA.md and delete the FNcompFN2, still haven't been able to merge the conflicting files and in the meanwhile made a mess of my branching :) locally and on my remote.



So this is not the right pull request anyone, PLS DO NOT ACCEPT THIS PULL REQUEST.

**Pull request closed without merging**
